# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 2.0"
gem "hanami-router", "~> 2.0"
gem "hanami-controller", "~> 2.0"
gem "hanami-validations", "~> 2.0"

gem "dry-types", "~> 1.0", ">= 1.6.1"
gem "dry-monads"
gem "puma"
gem "rake"

gem "phlex"
gem "vite_ruby"
gem "twilio-ruby", "~> 5.74.0"

gem "anycable", "~> 1.3"
gem "litecable", "~> 0.8"
gem "nats-pure"

group :development, :test do
  gem "dotenv"
  gem "pry-byebug"
end

group :cli, :development do
  gem "hanami-reloader"
end

group :cli, :development, :test do
  gem "hanami-rspec"
end

group :development do
  gem "guard-puma", "~> 0.8"
end

group :test do
  gem "rack-test"
end
