// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: internal/vosk/stt_service.proto

package vosk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SttServiceClient is the client API for SttService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SttServiceClient interface {
	StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (SttService_StreamingRecognizeClient, error)
}

type sttServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSttServiceClient(cc grpc.ClientConnInterface) SttServiceClient {
	return &sttServiceClient{cc}
}

func (c *sttServiceClient) StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (SttService_StreamingRecognizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SttService_ServiceDesc.Streams[0], "/vosk.stt.v1.SttService/StreamingRecognize", opts...)
	if err != nil {
		return nil, err
	}
	x := &sttServiceStreamingRecognizeClient{stream}
	return x, nil
}

type SttService_StreamingRecognizeClient interface {
	Send(*StreamingRecognitionRequest) error
	Recv() (*StreamingRecognitionResponse, error)
	grpc.ClientStream
}

type sttServiceStreamingRecognizeClient struct {
	grpc.ClientStream
}

func (x *sttServiceStreamingRecognizeClient) Send(m *StreamingRecognitionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sttServiceStreamingRecognizeClient) Recv() (*StreamingRecognitionResponse, error) {
	m := new(StreamingRecognitionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SttServiceServer is the server API for SttService service.
// All implementations must embed UnimplementedSttServiceServer
// for forward compatibility
type SttServiceServer interface {
	StreamingRecognize(SttService_StreamingRecognizeServer) error
	mustEmbedUnimplementedSttServiceServer()
}

// UnimplementedSttServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSttServiceServer struct {
}

func (UnimplementedSttServiceServer) StreamingRecognize(SttService_StreamingRecognizeServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingRecognize not implemented")
}
func (UnimplementedSttServiceServer) mustEmbedUnimplementedSttServiceServer() {}

// UnsafeSttServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SttServiceServer will
// result in compilation errors.
type UnsafeSttServiceServer interface {
	mustEmbedUnimplementedSttServiceServer()
}

func RegisterSttServiceServer(s grpc.ServiceRegistrar, srv SttServiceServer) {
	s.RegisterService(&SttService_ServiceDesc, srv)
}

func _SttService_StreamingRecognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SttServiceServer).StreamingRecognize(&sttServiceStreamingRecognizeServer{stream})
}

type SttService_StreamingRecognizeServer interface {
	Send(*StreamingRecognitionResponse) error
	Recv() (*StreamingRecognitionRequest, error)
	grpc.ServerStream
}

type sttServiceStreamingRecognizeServer struct {
	grpc.ServerStream
}

func (x *sttServiceStreamingRecognizeServer) Send(m *StreamingRecognitionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sttServiceStreamingRecognizeServer) Recv() (*StreamingRecognitionRequest, error) {
	m := new(StreamingRecognitionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SttService_ServiceDesc is the grpc.ServiceDesc for SttService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SttService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vosk.stt.v1.SttService",
	HandlerType: (*SttServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingRecognize",
			Handler:       _SttService_StreamingRecognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/vosk/stt_service.proto",
}

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatsResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/vosk.stt.v1.StatsService/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility
type StatsServiceServer interface {
	GetStats(context.Context, *emptypb.Empty) (*StatsResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatsServiceServer struct {
}

func (UnimplementedStatsServiceServer) GetStats(context.Context, *emptypb.Empty) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vosk.stt.v1.StatsService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vosk.stt.v1.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _StatsService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/vosk/stt_service.proto",
}
