# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/vosk/stt_service.proto for package 'vosk.stt.v1'

require 'grpc'
require_relative 'stt_service_pb'

module Vosk
  module Stt
    module V1
      module SttService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'vosk.stt.v1.SttService'

          rpc :StreamingRecognize, stream(::Vosk::Stt::V1::StreamingRecognitionRequest), stream(::Vosk::Stt::V1::StreamingRecognitionResponse)
        end

        Stub = Service.rpc_stub_class
      end
      module StatsService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'vosk.stt.v1.StatsService'

          rpc :GetStats, ::Google::Protobuf::Empty, ::Vosk::Stt::V1::StatsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
