# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/vosk/stt_service.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/vosk/stt_service.proto", :syntax => :proto3) do
    add_message "vosk.stt.v1.StreamingRecognitionRequest" do
      oneof :streaming_request do
        optional :config, :message, 1, "vosk.stt.v1.RecognitionConfig"
        optional :audio_content, :bytes, 2
      end
    end
    add_message "vosk.stt.v1.StreamingRecognitionResponse" do
      repeated :chunks, :message, 1, "vosk.stt.v1.SpeechRecognitionChunk"
    end
    add_message "vosk.stt.v1.RecognitionConfig" do
      optional :specification, :message, 1, "vosk.stt.v1.RecognitionSpec"
    end
    add_message "vosk.stt.v1.RecognitionSpec" do
      optional :audio_encoding, :enum, 1, "vosk.stt.v1.RecognitionSpec.AudioEncoding"
      optional :sample_rate_hertz, :int64, 2
      optional :language_code, :string, 3
      optional :profanity_filter, :bool, 4
      optional :model, :string, 5
      optional :partial_results, :bool, 7
      optional :single_utterance, :bool, 8
      optional :raw_results, :bool, 10
      optional :max_alternatives, :int32, 11
      optional :enable_word_time_offsets, :bool, 12
    end
    add_enum "vosk.stt.v1.RecognitionSpec.AudioEncoding" do
      value :AUDIO_ENCODING_UNSPECIFIED, 0
      value :LINEAR16_PCM, 1
    end
    add_message "vosk.stt.v1.SpeechRecognitionChunk" do
      repeated :alternatives, :message, 1, "vosk.stt.v1.SpeechRecognitionAlternative"
      optional :final, :bool, 2
      optional :end_of_utterance, :bool, 3
    end
    add_message "vosk.stt.v1.SpeechRecognitionAlternative" do
      optional :text, :string, 1
      optional :confidence, :float, 2
      repeated :words, :message, 3, "vosk.stt.v1.WordInfo"
    end
    add_message "vosk.stt.v1.WordInfo" do
      optional :start_time, :message, 1, "google.protobuf.Duration"
      optional :end_time, :message, 2, "google.protobuf.Duration"
      optional :word, :string, 3
      optional :confidence, :float, 4
    end
    add_message "vosk.stt.v1.StatsResponse" do
      optional :n_streams, :int32, 1
      optional :n_total_streams, :int32, 2
      optional :max_chunk_rtf, :float, 4
      optional :max_stream_rtf, :float, 6
    end
  end
end

module Vosk
  module Stt
    module V1
      StreamingRecognitionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.StreamingRecognitionRequest").msgclass
      StreamingRecognitionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.StreamingRecognitionResponse").msgclass
      RecognitionConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.RecognitionConfig").msgclass
      RecognitionSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.RecognitionSpec").msgclass
      RecognitionSpec::AudioEncoding = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.RecognitionSpec.AudioEncoding").enummodule
      SpeechRecognitionChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.SpeechRecognitionChunk").msgclass
      SpeechRecognitionAlternative = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.SpeechRecognitionAlternative").msgclass
      WordInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.WordInfo").msgclass
      StatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vosk.stt.v1.StatsResponse").msgclass
    end
  end
end
